### PR TITLE
Security update

### PR DESCRIPTION
**Pull request by Szaki**
This PR upgrades dependencies in order to weed out vulnerabilities.

### CODE REVIEW

**Comment by BBooijLiewes** [comment]
hey @Szaki may be nice to in this PR also build the `dist/` and test that on a bigger project? That would give us more certainty that all the updates were do here actually work.

**Comment by Szaki** [comment]
> hey @Szaki may be nice to in this PR also build the `dist/` and test that on a bigger project? That would give us more certainty that all the updates were do here actually work.

I think the tests are pretty extensive. I can include the update in the IAE PR, if that's good enough for you.

**Comment by BBooijLiewes** [comment]
hey @Szaki if you could 

> > hey @Szaki may be nice to in this PR also build the `dist/` and test that on a bigger project? That would give us more certainty that all the updates were do here actually work.
> 
> @BBooijLiewes I think the tests are pretty extensive. I can include the update in my related IAE PR, if that's good enough for you.

hey @Szaki if you could do that as a final step and there all the tests pass then I am OK with merging :+1: .

**Comment by Szaki** [comment]
@BBooijLiewes IAE is passing on this version

**Pull request merged**
